# -*- coding: utf-8 -*-
"""2.00 Netflix - Data Exploration and Visualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zowfS84i-dd6wqOL3Kg_B05w7Yb2vJt

Objectives of the Project:-
Perform EDA on the given dataset and find insights.
Provide Useful Insights and Business recommendations that can help the business to grow.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/drive/MyDrive/1.00 BUSNINESS CASE STUDY/2.00 NEXT FLIX BUSINESS CASE STUDY/netflix.CSV")

display(df.head(1))

df.shape

df.info()

df.describe()

"""From the above result, it is observed that only release date are numerical remaining features are categorical column."""

df.describe(include='object')

"""2. Data Cleaning"""

df.isna().sum()

"""From the above result it is boserved that in  2634 records , director name is missing,in 825 records cast is missing,in 831 records country is missing ,in 4 records rating is missing and in 3 records duration is missing"""

df.duration.value_counts()

"""From the above it is observed that instead of rating , by mistake it is it is entered duration."""

df[df.duration.isna()]

"""Now i replace the rating entry to duration."""

x=df[df.duration.isna()].index

df.loc[x]=df.loc[x].fillna(method='ffill',axis=1)

# replaced the wrong entries done in the rating column
df.loc[x ,'rating'] = 'Not Available'

df.loc[x]

"""Now filling the Null values of rating columns"""

df[df.rating.isna()]

xrating=df[df.rating.isna()].index
xrating

df.loc[xrating,'rating']='Not Available'

df.loc[xrating]

df.rating.unique()

"""Here NR (Not rated)  and UR(un rated),both are same. I am going to replace it with Not Available"""

df.loc[df.rating =='NR','rating' ]='Not Available'
df.rating.value_counts()

df.loc[df.rating =='UR','rating' ]='Not Available'
df.rating.value_counts()

"""Now dropping the null from date_added column"""

df.drop(df.loc[df.date_added.isna()].index,axis =0,inplace=True)
df.date_added.value_counts()

"""As 'date_added' feature are in date,but it is avaliable in object format ,So i will convert it in pandas date format by using pd.to_datetime(df.column)."""

df['date_added']=df['date_added'].str.strip().replace(r'\s+', ' ', regex=True)

df['date_added']=pd.to_datetime(df['date_added'],format='%B %d, %Y')
display(df['date_added'])

"""Creating a New feature of Year  by extracting the year from 'date_added' column"""

df['year']=df.date_added.dt.year
display(df['year'].head(2))

"""Creating a New feature of Month by extracting the Month from 'date_added' column"""

df['month']=df['date_added'].dt.month
df.month.head(2)

df[['date_added','year','month']].info()

"""Percentage of  Null values in each column"""

np.round(100*df.isna().sum()/df.shape[0],2)

"""3. Data Exploration and Non Graphical Analysis"""

df.type.value_counts()

# Types of contents.
# There are two types of content one is Movie and other one is TV Show.
# there percentage are shown bellow.
np.round(100*df.type.value_counts()/df.shape[0],2)

movies=df.loc[df['type']=='Movie']
tv_show=df.loc[df['type']=='TV Show']

movies.duration.value_counts()

tv_show.duration.value_counts()

"""As movies and TV show duration are in different format. We modify the the duration for movies as minutes and TV shows in seasion in similar format ."""

movies.duration=movies.duration.str[: -3]
movies.duration=movies.duration.astype('float')

movies.duration.value_counts()

tv_show['duration'] = tv_show.duration.str[:-7].apply(lambda x : x.strip())
tv_show['duration'] = tv_show['duration'].astype('float')

tv_show['duration'].head(3)

movies.rename({'duration':'Duration in Minuts'},axis=1,inplace=True)
tv_show.rename({'duration':'Duration in Seasion'},axis=1,inplace=True)

display(movies.head(2))

display(tv_show.head(1))

""" date of first movie added on netflix and  most recent movie added on netflix as per data i.e. dataset duration"""

movies_age=pd.DataFrame((movies.date_added.min().strftime('%B-%Y'),movies.date_added.max().strftime('%B-%Y')))
movies_age.index=['First Movies Uploaded Date','Last Movies Uploaded date']
display(movies_age)

print("First Movies Uplaoded at Netflix",movies[movies.date_added==movies.date_added.min()]['title'])

print("Last Movies Uplaoded at Netflix",movies[movies.date_added==movies.date_added.max()]['title'])

TV_Show_age=pd.DataFrame((tv_show.date_added.min().strftime('%B-%Y'),tv_show.date_added.max().strftime('%B-%Y')))
TV_Show_age.index=['First TV_show Uploaded Date','Last TV_show Uploaded date']
display(TV_Show_age)

print(" TV Show Uplaoded at first year at Netflix",tv_show[tv_show.date_added==tv_show.date_added.min()]['title'])

print("TV Show Uplaoded recently at Netflix",tv_show[tv_show.date_added==tv_show.date_added.max()]['title'])

""" Check the number of content released in each rating."""

df.groupby(by=['type','rating'])['show_id'].count()

"""Find the featutres  having maximum null values(records) and the feature having comma separated multiple values for each record"""

df['country'].value_counts()

"""From the avove result it has been observed that a movie has produces in more than one country. to analyse the data at country level it is deficult. So, we split the data on country level.
Creating a separate table for country , to avoid the duplicasy of records in our origional table after exploding.
"""

country_level=df[['show_id','country','type']]
country_level.dropna(axis=0,inplace=True)

country_level['country']=country_level['country'].apply(lambda x:x.split(','))
country_level=country_level.explode(['country'])
country_level

"""Removing the space from the country name"""

country_level['country']=country_level['country'].str.strip()

country_level=country_level[['show_id','type','country']]

"""Finding the list of show having blank country"""

country_level.loc[country_level['country']=='']

country_level.country.nunique()

"""Netflix have movies from 123 No country."""

y=country_level.groupby(by=['country','type'])['show_id'].count().reset_index()
y.pivot(index='country',columns='type',values='show_id').sort_values(by='Movie',ascending=False)

"""Working on Director Columns"""

df.director.value_counts()

"""Again observed here single movies are directed by multiple director."""

df_dir=df[['show_id','type','director']]
df_dir.dropna(inplace=True)

df_dir['director']=df_dir['director'].apply(lambda x: x.split(','))
df_dir.head()

df_dir=df_dir.explode('director')

df_dir.director=df_dir.director.str.strip()

df_dir[df_dir.director=='']

df_dir

df_dir.director.nunique()

"""Movies and TV shows directed by each director"""

xdirector=df_dir.groupby(by=['director','type'])['show_id'].count().reset_index()
xdirector.pivot(index='director',columns='type',values='show_id').sort_values(by='Movie',ascending=False)

"""Working on cast"""

df_cast=df[['show_id','type','cast']]
df_cast.dropna(inplace=True)

df_cast.value_counts()

df_cast['cast']=df_cast['cast'].apply(lambda x: x.split(','))

df_cast=df_cast.explode('cast')

df_cast.cast

df_cast.cast=df_cast.cast.str.strip()

df_cast[df_cast.cast=='']

df_cast.cast

df_cast.duplicated().sum()

df_cast.drop_duplicates()

df_cast_group=df_cast.groupby(by=['cast','type'])['show_id'].count().reset_index()
df_cast_group.pivot(index='cast',columns='type',values='show_id').sort_values(by='TV Show',ascending=False)

"""Visual Analysis - Univariate & Bivariate

Distribution of content across the different types
"""

types=df.type.value_counts()
plt.pie(types, labels=types.index,autopct='%1.1f%%')
plt.title('Percetage of Movies & TV Shows')
plt.show()

"""It is observed that , around 70% content is Movies and around 30% content is TV shows.
4.2 Distribution of 'date_added' column
How has the number of movies/TV shows added on Netflix per year changed over the time?

Year Wise No of Movies and TV Shows detaisl
"""

xgr=df.groupby(by=['year','type'])['show_id'].count().reset_index()
xgr.rename({'show_id' : "total movies/TV shows"},axis=1,inplace=True)
xgr.head()

sns.lineplot(y=xgr['total movies/TV shows'],x=xgr['year'],hue=xgr['type'],marker='o')
plt.title(" Year Wise No of Movies & TV Show")

"""Observation:

From the graph it is ovserved that content increases drasticaaly at 2015.

In the year 2019, highest number of movies and TV shows added on the Netflix.

After 2019 no of content has reduced remarkable may be because of pandanamic.

# Distribution of content accordingly relaes year
"""

dfrls=df.groupby(by=['release_year','type'])['show_id'].count().reset_index()
dfrls.head(2)

plt.figure(figsize=(10,6))
sns.lineplot(x=dfrls['release_year'],y=dfrls['show_id'],hue=dfrls['type'])
plt.title("release_year vs show_id")
plt.xlim( left = 2000 , right = 2021)
plt.xticks(np.arange(2000 , 2021 , 2))
plt.show()

"""Observation:
from grap it is shown
In year 2015 , the number of movies inceases drastically.

in year 2018 , the highest number of movie and TV show releases.

Since 2018, A drop in movies is seen and rise in TV shows is observed clearly, and TV shows surpasses the movies count in mid 2020.
"""

#Director wise number of movies

df_dirmov=df['director'].value_counts().head(10).reset_index()
df_dirmov

plt.figure(figsize=(8,5))
sns.barplot(x=df_dirmov['count'],y=df_dirmov['director'])
plt.title("Top 10 Director")
plt.ylabel("Director Name")
plt.xlabel('Movie/TV Show Count')

"""Observation:

Rajiv Chilaka, Jan Suter and  Raúl Campos are the top 3 directors on Netflix.
"""

country_level.country.value_counts()

top_10_country=country_level.country.value_counts().head(10).index
df_new=country_level.loc[country_level['country'].isin(top_10_country)]
df_new

df_new.head(4)

y=df_new.groupby(by=['country','type'])['show_id'].count().reset_index()
y.pivot(index='country',columns='type',values='show_id').sort_values(by='Movie',ascending=False)

plt.figure(figsize= (8,5))
sns.countplot(data = df_new , x = 'country' , order = top_10_country , hue = 'type')
plt.xticks(rotation = 90 , fontsize = 12)
plt.ylabel('Total_movies/TV shows' ,color='orange' ,fontsize = 15)
plt.xlabel('Country Name',color='g',fontsize=14)
plt.title('Total_movies/TVshows_by_country')
plt.show()

top_10_country=y.country.value_counts().head(10).index
country_level['cat']=country_level['country'].apply(lambda x: x if x in top_10_country else ' Other country' )

x=country_level.cat.value_counts()
fig=plt.figure(figsize=(10,9))
plt.pie(x,labels=x.index,autopct="%1.1f%%")
plt.show()

"""Observation:
From pie chart is is observed that United States is the HIGHEST contributor country on Netflix, followed by India and United Kingdom.

Maximum content of Netflix which is around 75% , is coming from these top 10 countries. Rest of the world only contributes 25% of the content.
"""

plt.figure(figsize= (12,6))
sns.boxplot(data = df , x = 'release_year')
plt.xlabel('Release_year' , fontsize = 12)
plt.title('Year Wise Total Released Movies/TVshows')
plt.xticks(np.arange(1940 , 2021 , 10))
plt.xlim((1940 , 2022))
plt.show()

"""Major content which is released in the year range 2015-2021

## Bivariate Analysis

Checking  countries are adding more number of content over the time
"""

month_year = df.groupby(['year' , 'month'])['show_id'].count().reset_index()

plt.figure(figsize = (10,6))
sns.lineplot(data=month_year, x = 'year', y = 'show_id', hue='month',color='green')
plt.title('Year and Month of Adding Shows on Netflix')

country_list = country_level.country.value_counts().head(15).index
top_15_country = country_level.loc[country_level['country'].isin(country_list)]
country_year = top_15_country.merge(df , on = 'show_id')[['show_id','country_x' ,'type_x' , 'year' ]]
country_year.columns = ['show_id', 'country', 'type', 'year']

country_year = country_year.groupby(['country' , 'year'])['show_id'].count().reset_index()

plt.figure(figsize = (10,6))
sns.lineplot(data = country_year , x = 'year' , y = 'show_id' , hue = 'country' , palette ='rainbow' )

"""Observation :
United Stated have always added highset number of movies/TV shows over the time.
Since 2016, India has seen spike in popularity of content and added more number of content, followed by United Kingdom at 3rd position.

** Insights based on Non-Graphical and Visual Analysis**
Around 70% content on Netflix is Movies and around 30% content is TV shows.

The movies and TV shows uploading on the Netflix started from the year 2008, It had very lesser content till 2014.

Year 2015 marks the drastic surge in the content getting uploaded on Netflix.
It continues the uptrend since then and 2019 marks the highest number of movies and TV shows added on the Netflix.
Year 2020 and 2021 has seen the drop in content added on Netflix, possibly because of Pandemic. But still , TV shows content have not dropped as drastic as movies.
Since 2018, A drop in the movies is seen , but rise in TV shows is observed clearly. Being in continuous uptrend , TV shows surpassed the movies count in mid 2020. It shows the rise in popularity of tv shows in recent years.

Netflix has movies from variety of directors. Around 4993 directors have their movies or tv shows on Netflix.

Netflix has movies from total 122 countries, United States being the highset contributor with almost 37% of all the content.

The release year for shows is concentrated in the range 2005-2021.
50 mins - 150 mins is the range of movie durations, excluding potential outliers.

Content in most of the ratings is available in lesser quanitity except in US. Ratings like TV-Y7 , TV-Y7 FV , PG ,TV-G , G , TV-Y , TV-PG are very less avaialble in all countries except US.

Shorter duration movies have been popular in last 10 years.

**Business Insights**
Netflix have majority of content which is released after the year 2000. It is observed that the content older than year 2000 is very scarce on Netflix.

Senior Citizen could be the target audience for such content, which is almost missing currently.

Maximum content (more than 80%) is
TV-MA - Content intended for mature audiences aged 17 and above.
TV-14 - Content suitable for viewers aged 14 and above.
TV-PG - Parental guidance suggested (similar ratings - PG-13 , PG)
R - Restricted Content, that may not be suitable for viewers under age 17.
These ratings' movies target Matured and Adult audience. Rest 20 % of the content is for kids aged below 13. It shows that Netflix is currently serving mostly Mature audiences or Children with parental guidance.

drop in content is seen across all the countries and type of content in year 2020 and 2021, possibly because of Pandemic.

**Recommendations**

Country specific insights -
    The content need to be targetting the demographic of any country. Netflix can produce higher number of content in the perticular rating as per demographic of the country. Eg.
    The country like India , which is highly populous , has maximum content available only in three rating TV-MA, TV-14 , TV-PG. It is unlikely to serve below 14 age and above 35 year age group .
"""

